config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    root 'registrations#new'
  end

  devise_for :users, 
             :controllers => { :registrations => "registrations",
                               :omniauth_callbacks => "omniauth_callbacks" },
             :skip => [:sessions]
  as :user do
    get    'login'  => 'devise/sessions#new',     :as => :new_user_session
    post   'login'  => 'devise/sessions#create',  :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get    'signup' => 'registrations#new'
    get '/unused_email', to: 'registrations#unused_email'
  end

  resources :users,         only: [:index]
  resources :friendships,   only: [:create, :update, :destroy]
  resources :notifications, only: [:index]
  resources :posts,         only: [:create, :destroy]
  resources :comments,      only: [:create, :destroy, :index]
  resources :likes,         only: [:create, :destroy]
  resources :profiles,      only: [:show, :edit, :update]

  get 'newsfeed/:id',        to: 'users#newsfeed',        as: :newsfeed
  get 'newsfeed/:id',        to: 'users#newsfeed',        as: :user_root
  get 'timeline/:id',        to: 'users#timeline',        as: :timeline
  get 'friends/:id',         to: 'users#friends',         as: :friends
  get 'friend_requests/:id', to: 'users#friend_requests', as: :friend_requests
  get 'find_friends/:id',    to: 'users#find_friends',    as: :find_friends
  get 'search',              to: 'users#search',          as: :search
  get 'comments/add/:id',    to: 'comments#add'
  post 'posts/add',          to: 'posts#add'
  get 'notifications/update_new', to: 'notifications#update_new'
  post 'likes/create_destroy',    to: 'likes#create_destroy'

  get 'about',        to: 'static_pages#about',        as: :about
  get 'contact_help', to: 'static_pages#contact_help', as: :contact_help
  get 'privacy',      to: 'static_pages#privacy',      as: :privacy
  get 'terms',        to: 'static_pages#terms',        as: :terms

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!
  
  def about
  end

  def contact_help
  end

  def privacy
  end

  def terms
  end
end

app/views/static_pages/_footer.html.haml
.footer-container
  %footer.signup-footer
    %ul
      %li= link_to "About",            about_path
      %li= link_to "Contact / Help",   contact_help_path
      %li= link_to "Privacy",          privacy_path
      %li= link_to "Terms of Service", terms_path
      - if user_signed_in?
        %li= link_to "Log Out", destroy_user_session_path, method: :delete
      - else
        %li= link_to "Log In",  new_user_session_path
        %li= link_to "Sign Up", signup_path

    %p Odinbook &copy; 2015

app/views/static_pages/about.html.haml
- provide(:title, "About Odinbook")

.static-content
  %h2 About Us
  %p 
    Odinbook is a personal project created to help with learning web development. It was made as the final project of <a href="http://www.theodinproject.com/home">The Odin Project</a>'s <a href="http://www.theodinproject.com/ruby-on-rails/final-project">Ruby on Rails</a> and <a href="http://www.theodinproject.com/javascript-and-jquery/final-project">JavaScript/jQuery</a> courses.
  %p 
    Odinbook is made to replicate some of the look and functionality of Facebook, but is not affiliated with Facebook.
  %p
    We aim to be unobtrusive and privacy-minded, storing no more than what you provide and allowing you to completely delete an account whenever you choose. See our
    = link_to "Privacy Policy", privacy_path
    for more details.
  %p 
    Odinbook is <a href="https://dna-odinbook.herokuapp.com/">hosted on Heroku</a> and the source code can be <a href="https://github.com/donaldali/odinbook">viewed on GitHub</a>.
  %p 
    To learn more about the features avaliable, please see the <a href="https://github.com/donaldali/odinbook#details-of-main-features">documentation on GitHub</a>.
  %p 
    Please leave any comments, feedback, concerns, or questions you have on the <a href="https://gist.github.com/donaldali/6670a7667dde9c7934c1">Odinbook Gist</a> or the <a href="https://github.com/donaldali/odinbook/wiki/Home/_edit">Odinbook Wiki</a>.

app/views/static_pages/contact_help.html.haml
- provide(:title, "Contact | Help")

.static-content
  %h2 Contact or Help
  %p 
    We would like to hear any kind of feedback (comment, concerns, issues, problems, suggestions, or whatever) you might have. Please leave them on the <a href="https://gist.github.com/donaldali/6670a7667dde9c7934c1">Odinbook Gist</a> or the <a href="https://github.com/donaldali/odinbook/wiki/Home/_edit">Odinbook Wiki</a>.
  %p 
    To report a problem or issue, you may also create a new <a href="https://github.com/donaldali/odinbook/issues/new">GitHub Issue</a>.

app/views/static_pages/privacy.html.haml
- provide(:title, "Privacy Policy")

.static-content
  %h2 Privacy Policy
  %h5 Last Updated: Mar 20, 2015

  %p
    This privacy policy discloses the privacy practices for Odinbook.

  %h3 What information we collect?
  %p 
    We collect information from you when you register on our site and when you fill out your profile. Personally identifying information collected include your name and email. Your email is hidden from everyone, but your name and profile picture (if you provide one) are shown to all Odinbook users.
  %p
    If you choose to register with an external service like Facebook, we collect ONLY your first name, last name, email, and gender; that is, exactly the information required to sign up for Odinbook. If you later log in with Facebook, only your email address will be used to log you in.
  %p
    Other than the information you provided during registration and at your profile, we keep no informtion about you. We store the content you generate on Odinbook (like posts or comments you make), but we don't store your log in times, locations, IP addresses or any information you don't explicitly create during your use of this service.

  %h3 What we use your information for?
  %p
    We use your email to log you into the website, send you a one time welcome email, and later emails about your notifications. You can disable receiving emails about notifications from your profile. You can choose, from your profile, to share your Odinbook created content with everyone (that is, all Odinbook users) or just your friends.

  %h3 Who we share your information with?
  %p
    We do not share, rent, sell, trade, or otherwise transfer any of your information with or to any third party including any non-identifying data or any aggregate data.

  %h3 Control over your information
  %p
    You can change any information related to your profile at anytime, including not providing any profile information. We do however require that you always have the information used to sign up (that is, your first name, last name, email, and gender).
  %p
    If for whatever reason you are not satisfied with Odinbook, you can delete your entire Odinbook account from your profile and the entirety of your activity will be erased. We will keep no record that you ever used our service.

  %h3 Third party links
  %p
    We do have links to a couple of third party websites. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activity of these linked sites.

  %h3 Changes to our Privacy Policy
  %p
    Any changes to our privacy policy will be posted on this page.

  %h3 Contacting Us
  %p
    You may address any comments, concerns, or issues to the <a href="https://gist.github.com/donaldali/6670a7667dde9c7934c1">Odinbook Gist</a> or the <a href="https://github.com/donaldali/odinbook/wiki/Home/_edit">Odinbook Wiki</a>.

app/views/static_pages/terms.html.haml
- provide(:title, "Terms of Service")

.static-content
  %h2 Terms of Service
  %h5 Last Updated: March 20, 2015.
  %p 
    Please read these Terms of Service ("Terms", "Terms and Conditions of Use") completely to use 
    = link_to "Odinbook.", root_path
    The term 'Odinbook' or 'us' or 'we' refers to the owner of the website. The term 'you' refers to the user or viewer of our website. If you continue to use this website, you are agreeing to comply with and be bound by the following Terms and Conditions of Use, which together with our 
    = link_to "Privacy Policy", privacy_path
    govern Odinbook's relationship with you in relation to this website. If you disagree with any part of these Terms and Conditions of Use, please do not use our website. 

  %h3 Terms and Conditions of Use
  %p 
    The use of this website is subject to the following Terms:
  %ul
    %li Don't use this website to do anything illegal or harmful.
    %li Treat others as you would like others to treat you.
    %li Don't treats others in ways you would not like to be treated.

  %h3 Termination
  %p 
    We reserve the right to terminate or suspend your access to the Site, immeidately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
  %p 
    All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.