config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    root 'registrations#new'
  end

  devise_for :users, 
             :controllers => { :registrations => "registrations",
                               :omniauth_callbacks => "omniauth_callbacks" },
             :skip => [:sessions]
  as :user do
    get    'login'  => 'devise/sessions#new',     :as => :new_user_session
    post   'login'  => 'devise/sessions#create',  :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get    'signup' => 'registrations#new'
    get '/unused_email', to: 'registrations#unused_email'
  end

  resources :users,         only: [:index]
  resources :friendships,   only: [:create, :update, :destroy]
  resources :notifications, only: [:index]
  resources :posts,         only: [:create, :destroy]
  resources :comments,      only: [:create, :destroy, :index]
  resources :likes,         only: [:create, :destroy]
  resources :profiles,      only: [:show, :edit, :update]

  get 'newsfeed/:id',        to: 'users#newsfeed',        as: :newsfeed
  get 'newsfeed/:id',        to: 'users#newsfeed',        as: :user_root
  get 'timeline/:id',        to: 'users#timeline',        as: :timeline
  get 'friends/:id',         to: 'users#friends',         as: :friends
  get 'friend_requests/:id', to: 'users#friend_requests', as: :friend_requests
  get 'find_friends/:id',    to: 'users#find_friends',    as: :find_friends
  get 'search',              to: 'users#search',          as: :search
  get 'comments/add/:id',    to: 'comments#add'
  post 'posts/add',          to: 'posts#add'
  get 'notifications/update_new', to: 'notifications#update_new'
  post 'likes/create_destroy',    to: 'likes#create_destroy'

  get 'about',        to: 'static_pages#about',        as: :about
  get 'contact_help', to: 'static_pages#contact_help', as: :contact_help
  get 'privacy',      to: 'static_pages#privacy',      as: :privacy
  get 'terms',        to: 'static_pages#terms',        as: :terms

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessor :delete_picture

  belongs_to :user

  validates :access_to,          presence: true
  validates :email_notification, inclusion: { in: [true, false] }

  has_attached_file :picture, 
      styles: { v_lg_img: "160x160#", lg_img: "75x75#",
                  md_img: "40x40#",   sm_img: "32x32#",
                v_sm_img: "19x19#" }

  validates_attachment :picture, 
      size: { less_than: 500.kilobytes, 
              message: "must be less than 500KB" },
      content_type: { content_type: /^image\/(jpe?g|png|gif)$/,
                      message: "must be .jpeg, .jpg, .png, or .gif" }
  
  after_validation :remove_duplicate_errors
  before_save      :delete_requested_picture


  private


  def remove_duplicate_errors
    errors.delete(:picture)
  end

  def delete_requested_picture
    self.picture = nil if delete_picture == "1" && 
                          !picture_updated_at_changed?
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :authorize_self_profile,   only: [:edit, :update]
  before_action :authorize_public_profile, only: [:show]

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = Profile.find(params[:id])

    if @profile.update(profile_params)
      redirect_to @profile, notice: "Profile updated."
    else
      render "edit"
    end
  end


  private

  
  def authorize_self_profile
    user = Profile.find(params[:id]).user
    msg  = "You can change only your profile"
    authorize_user!(user, :self, msg)
  end

  def authorize_public_profile
    user = Profile.find(params[:id]).user
    msg  = "#{user.first_name} only shares #{user.genderize} profile "\
           "information with friends"
    authorize_user!(user, :public, msg)
  end

  def profile_params
    params.require(:profile).permit(:picture,   :birthday,   :country,
                                    :education, :profession, :about_you,
                                    :access_to, :email_notification,
                                    :delete_picture)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper

  def display_friend_status_of user
    if current_user == user
      render "profiles/self"
    elsif current_user.has_friend_request_from?(user)
      render "profiles/request_received", user: user
    elsif user.has_friend_request_from?(current_user)
      render "profiles/request_sent"
    elsif current_user.friends_with?(user)
      render "profiles/current_friend", user: user
    else
      render "profiles/add_friend", user: user
    end
  end

  def no_friend_profile_message(user)
    if current_user == user
      "No friends yet...Send some friend requests"
    else
      "#{user.first_name} has no friends...consider sending "\
      "a friend request"
    end
  end

  def formatted_birthday birthday
    return "No birthday provided" if birthday.blank?

    birthday.strftime('%B %-d')
  end

  def country_name country_code
    return "No country specified" if country_code.blank?

    country = ISO3166::Country[country_code]
    country.translations[I18n.locale.to_s] || country.name
  end

  def value_or_none value
    return "None specified" if value.blank?

    value
  end

  def bool_to_yes_no bool
    return "Yes" if bool
    "No"
  end

  def get_education_options
    [["Some High School", "Some High School"], 
     ["High School Graduate", "High School Graduate"], 
     ["Some College", "Some College"], 
     ["Bachelor's Degree", "Bachelor's Degree"], 
     ["Post Graduate Degree", "Post Graduate Degree"]]
  end

  def get_profession_options
    [["Aspiring Developer", "Aspiring Developer"], 
     ["Practicing Developer", "Practicing Developer"], 
     ["Computer Related, Not Developer", 
      "Computer Related, Not Developer"],
     ["Science Related, Not Computer Related", 
      "Science Related, Not Computer Related"],
     ["Not Science Related, I Have a Life", 
      "Not Science Related, I Have a Life"]]
  end
end

app/views/profiles/_add_friend.html.haml
%p
  = "Do you know #{user.first_name}?"
  = render "users/add_friend", user: user, is_index: true

app/views/profiles/_current_friend.html.haml
%p= "Friends with #{user.first_name}"

app/views/profiles/_form_errors.html.haml
- if profile.errors.any?
  .error-container#error_explanation

    %h3= "Please fix the #{'problem'.pluralize(profile.errors.count)} below"
    %ul
      - profile.errors.full_messages.each do |message|
        %li= message

app/views/profiles/_request_received.html.haml
%p= "Friend request from #{user.first_name}"
%p= link_to "See your friend requests", friend_requests_path(current_user)

app/views/profiles/_request_sent.html.haml
%p= "Friend request pending"

app/views/profiles/_self.html.haml
%p= link_to "Update your Profile", edit_profile_path(current_user)

app/views/profiles/edit.html.haml
- provide(:title, @profile.user.name)

.profile-container
  %h2 Edit Profile

  = render "form_errors", profile: @profile

  .edit-profile-form
    = form_for @profile, html: { multipart: true } do |f|
      .general
        %div{class: ("field_with_errors" if @profile.errors.any?)}
          = f.label :picture
          = f.file_field :picture

        - if @profile.picture?
          .delete-picture
            = f.check_box :delete_picture
            = f.label :delete_picture, "Delete Current Picture"

        .bday
          = f.label :birthday
          = f.date_select :birthday, discard_year: true, 
                           use_short_month: true, prompt: true

        %div
          = f.label :country
          = f.country_select :country, priority_countries: ["US"], 
                              prompt: "Select Country", include_blank: true

        %div
          = f.label :education
          = f.select :education, get_education_options, 
                      prompt: "Select Education Level", include_blank: true

        %div
          = f.label :profession
          = f.select :profession, get_profession_options, 
                      prompt: "Select Profession", include_blank: true

        %div
          = f.label :about_you
          = f.text_area :about_you

      .privacy
        %h3 Privacy
        %div
          %span Who can view your Profile and Posts
          = f.radio_button :access_to, ACCESS[:all]
          = f.label :access_to_all_users, ACCESS[:all]
          = f.radio_button :access_to, ACCESS[:friends]
          = f.label :access_to_friends, ACCESS[:friends]

        %div
          %span Receive email of notifications?
          = f.radio_button :email_notification, true
          = f.label :email_notification_true, "Yes"
          = f.radio_button :email_notification, false
          = f.label :email_notification_false, "No"

      .center
        = f.submit class: "primary-btn"
        = link_to "Cancel", @profile, class: "default-btn"

  = button_to "Delete Odinbook Account", registration_path(current_user),   |
      data: { confirm: "This will completely delete your entire Odinbook "  |
                       "account (not just your profile). \n There will be " |
                       "no way to recover any part of your account. \n "    |
                       "Are you absolutely sure you want to proceed?" },    |
      method: :delete, class: "destroy-btn"                                 |

app/views/profiles/friends.html.haml
- user    = User.find(@receiver_id)
- friends = @users
- provide(:title, user.name)

%ul.users-container
  %li.friends-header
    %h2
      = "#{user.first_name}'s friends"
      %span= "#{friends.count}"

  = render friends, is_index: @is_index

  - if friends.empty?
    %li.empty-list= no_friend_profile_message(user)

= will_paginate @users

app/views/profiles/show.html.haml
- provide(:title, @profile.user.name)

.profile-container
  %h2= "About #{@profile.user.first_name}"

  .show-profile-container
    .show-general
      %div
        %span Gender: 
        %span= "#{@profile.user.gender.capitalize}"

      %div
        %span Birthday: 
        %span= "#{formatted_birthday @profile.birthday}"

      %div
        %span Country: 
        %span= "#{country_name @profile.country}"

      %div
        %span Education: 
        %span= "#{value_or_none @profile.education}"

      %div
        %span Profession: 
        %span= "#{value_or_none @profile.profession}"

      %div
        %span= "About #{@profile.user.first_name}: "
        %span= "#{value_or_none @profile.about_you}"

    - if access_level?(@profile.user, :self)
      .show-privacy
        %div
          %span Who has access to your Profile and Posts: 
          %span= "#{@profile.access_to}"

        %div
          %span Will you receive email of notifications: 
          %span= "#{bool_to_yes_no @profile.email_notification}"

      .show-bottom
        %div
        = link_to "Edit Your Profile", edit_profile_path(current_user.profile)