config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    root 'registrations#new'
  end

  devise_for :users, 
             :controllers => { :registrations => "registrations",
                               :omniauth_callbacks => "omniauth_callbacks" },
             :skip => [:sessions]
  as :user do
    get    'login'  => 'devise/sessions#new',     :as => :new_user_session
    post   'login'  => 'devise/sessions#create',  :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get    'signup' => 'registrations#new'
    get '/unused_email', to: 'registrations#unused_email'
  end

  resources :users,         only: [:index]
  resources :friendships,   only: [:create, :update, :destroy]
  resources :notifications, only: [:index]
  resources :posts,         only: [:create, :destroy]
  resources :comments,      only: [:create, :destroy, :index]
  resources :likes,         only: [:create, :destroy]
  resources :profiles,      only: [:show, :edit, :update]

  get 'newsfeed/:id',        to: 'users#newsfeed',        as: :newsfeed
  get 'newsfeed/:id',        to: 'users#newsfeed',        as: :user_root
  get 'timeline/:id',        to: 'users#timeline',        as: :timeline
  get 'friends/:id',         to: 'users#friends',         as: :friends
  get 'friend_requests/:id', to: 'users#friend_requests', as: :friend_requests
  get 'find_friends/:id',    to: 'users#find_friends',    as: :find_friends
  get 'search',              to: 'users#search',          as: :search
  get 'comments/add/:id',    to: 'comments#add'
  post 'posts/add',          to: 'posts#add'
  get 'notifications/update_new', to: 'notifications#update_new'
  post 'likes/create_destroy',    to: 'likes#create_destroy'

  get 'about',        to: 'static_pages#about',        as: :about
  get 'contact_help', to: 'static_pages#contact_help', as: :contact_help
  get 'privacy',      to: 'static_pages#privacy',      as: :privacy
  get 'terms',        to: 'static_pages#terms',        as: :terms

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :commenter, class_name: 'User'
  has_many   :likes, as: :likeable, dependent: :destroy

  validates :content,      presence: true
  validates :post_id,      presence: true
  validates :commenter_id, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CommentsHelper

  before_action :authorize_friend_post_creator_receiver, only: [:create]
  before_action :authorize_self_comment, only: [:destroy]

  def index
    @post_id  = params[:post_id]
    @comments = Post.find(@post_id).comments
    respond_to { |format| format.js } 
  end

  def create
    content  = params[:comment][:content]
    @comment = current_user.comments.create(content: content, 
                 post_id: params[:post_id]) unless content.blank?

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
    WebsocketRails[:updates].trigger(:add_comment, 
                             comment_info(@comment) ) unless @comment.nil?
  end

  def destroy
    @comment       = Comment.find(params[:id])
    comment_dom_id = comment_dom_id(@comment)
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
    WebsocketRails[:updates].trigger(:remove_comment, 
                                      comment_dom_id: comment_dom_id)
  end

  def add
    @comment = Comment.find(params[:id])
    render 'create'
  end


  private


  def authorize_self_comment
    user = Comment.find(params[:id]).commenter
    msg  = "You can only delete comments you created."
    authorize_user!(user, :self, msg)
  end

  def authorize_friend_post_creator_receiver
    post     = Post.find(params[:post_id])
    creator  = post.creator
    receiver = post.receiver
    msg      = "You can only comment on posts by or to you or your friends."

    authorize_either_user!(creator, receiver, :friend, msg)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
  def dom_parent_id comment 
    "post-#{ comment.post.id }-comments"
  end

  def comment_dom_id comment
    "comment-#{ comment.id }"
  end

  def comment_info comment
    { id: comment.id, dom_parent_id: dom_parent_id(comment) }
  end
end

app/views/comments/_comment.html.haml
- commenter = comment.commenter
%li.comment-container{ id: "comment-#{ comment.id }" }
  .comment-details
    = render "comments/comment_delete", comment: comment, commenter: commenter

    = link_to timeline_path(commenter) do
      = image_for(commenter, options = { img_class: "sm-img"})
    .info
      = link_to "#{commenter.name}", timeline_path(commenter)
      %span= comment.content

      %p
        = format_datetime(comment.created_at)

        %span.dot= "."
        %span.comment-like{ id: "comment-#{comment.id}-like" }
          = render "likes/like_link", likeable_id: comment.id, 
                                      likeable_type: "Comment"

        %span{ id: "comment-#{comment.id}-likers"}
          = render "comments/comment_likers", comment: comment

app/views/comments/_comment_delete.html.haml
- if current_user == commenter
  = link_to comment_path(comment), method: :delete, class: "delete",
                                   remote: true do
    = image_tag("close.png", title: "Delete Comment")

app/views/comments/_comment_likers.html.haml
- likes = comment.likes.count
- if likes > 0
  %span.dot= "."
  = image_tag "like.png", class: "like-img"
  = "#{likes}"

app/views/comments/create.js.haml
- dom_parent_id = dom_parent_id(@comment)
- unless @comment.nil?
  :plain
    if( $("##{ comment_dom_id(@comment) }").length === 0 ) {
      $("#{ escape_javascript(render @comment) }")
        .appendTo("##{ dom_parent_id }").hide().fadeIn();

      $("##{ dom_parent_id }").closest("li").find("input[type='text']").val("");
    }

app/views/comments/destroy.js.haml
:plain
  $("##{comment_dom_id(@comment)}").fadeOut(300, function() {
    $(this).remove();
    $(window).trigger('contentSizeReduced');
  });

app/views/comments/index.js.haml
:plain
  $("#post-#{@post_id}-comments").html("#{ escape_javascript(render @comments) }");

app/views/comments/new.html.haml
.comment-form
  = link_to timeline_path(current_user) do
    = image_for(current_user, options = { img_class: "sm-img"})
  = form_for(post.comments.build, remote: true) do |f|
    = hidden_field_tag :post_id, post.id
    .comment-label= f.label :content, class: "sr-only"
    .comment-input= f.text_field :content, placeholder: "Write a comment...", | 
                                           title: "Write a comment..."        |
    = f.submit "Comment", class: "sr-only"