config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    root 'registrations#new'
  end

  devise_for :users, 
             :controllers => { :registrations => "registrations",
                               :omniauth_callbacks => "omniauth_callbacks" },
             :skip => [:sessions]
  as :user do
    get    'login'  => 'devise/sessions#new',     :as => :new_user_session
    post   'login'  => 'devise/sessions#create',  :as => :user_session
    delete 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    get    'signup' => 'registrations#new'
    get '/unused_email', to: 'registrations#unused_email'
  end

  resources :users,         only: [:index]
  resources :friendships,   only: [:create, :update, :destroy]
  resources :notifications, only: [:index]
  resources :posts,         only: [:create, :destroy]
  resources :comments,      only: [:create, :destroy, :index]
  resources :likes,         only: [:create, :destroy]
  resources :profiles,      only: [:show, :edit, :update]

  get 'newsfeed/:id',        to: 'users#newsfeed',        as: :newsfeed
  get 'newsfeed/:id',        to: 'users#newsfeed',        as: :user_root
  get 'timeline/:id',        to: 'users#timeline',        as: :timeline
  get 'friends/:id',         to: 'users#friends',         as: :friends
  get 'friend_requests/:id', to: 'users#friend_requests', as: :friend_requests
  get 'find_friends/:id',    to: 'users#find_friends',    as: :find_friends
  get 'search',              to: 'users#search',          as: :search
  get 'comments/add/:id',    to: 'comments#add'
  post 'posts/add',          to: 'posts#add'
  get 'notifications/update_new', to: 'notifications#update_new'
  post 'likes/create_destroy',    to: 'likes#create_destroy'

  get 'about',        to: 'static_pages#about',        as: :about
  get 'contact_help', to: 'static_pages#contact_help', as: :contact_help
  get 'privacy',      to: 'static_pages#privacy',      as: :privacy
  get 'terms',        to: 'static_pages#terms',        as: :terms

end

app/views/layouts/_banner.html.haml
- user = (@profile && @profile.user) || User.find(@receiver_id)

.profile-banner
  .banner-top
    %span= link_to "#{user.name}", timeline_path(user)
    .friend-status{id: "friend-status-#{user.id}"}
      = display_friend_status_of(user)

  .banner-bottom
    %ul
      %li>= link_to "Timeline", timeline_path(user)
      - if access_level?(user, :public)
        %li>= link_to "About", profile_path(user.profile)
        %li
          = link_to friends_path(user, from: "profile") do
            %span Friends
            %span.friend-count= user.friends.count
  .profile-pic
    = render "layouts/banner_image", user: user

app/views/layouts/_banner_image.html.haml
- if current_user == user
  = link_to edit_profile_path(user.profile) do
    = image_for(user, options = { img_class: "v-lg-img",             |
                                  title: "Update Profile Picture" }) |
- else
  = link_to timeline_path(user) do
    = image_for(user, options = { img_class: "v-lg-img", title: "#{user.name}" })

app/views/layouts/_flash.html.haml
- if flash.any?
  - flash.each do |type, message|
    -# Don't display Devise's timedout flash message
    - unless message.blank? || type == 'timedout' || type == 'html_safe'
      .flash-holder
        .flash{class: "#{type}"}
          = message

app/views/layouts/_footer.html.haml
- if controller == "static_pages" || controller == "registrations" || |
                                      controller == "devise/sessions" |
  = render "static_pages/footer"

app/views/layouts/_header.html.haml
.main-header
  .header-holder
    = link_to newsfeed_path(current_user) do
      = image_tag "icon.png", alt: "Odinbook icon", class: "icon"
    .header-form
      = form_tag search_path, method: :get do
        = search_field_tag(:q, params[:q], placeholder: "Search Odinbook")
        = button_tag name: nil, class: "search-btn" do
          = image_tag "search-icon.png", class: "search-icon"
    .header-menu
      %ul
        %li>
          .header-profile{ title: "Profile" }
            = link_to timeline_path(current_user) do
              = image_for(current_user, options = { img_class: "v-sm-img" })
              %span= "#{current_user.first_name}"
        %li>= link_to "Home", newsfeed_path(current_user)
        %li>= link_to "Find Friends", find_friends_path(current_user)
        %li>
          = link_to notifications_path do
            = "Notifications"
            
            #new-notification-count
              = render "layouts/new_notifications"
            
            .notification-notice
              %div NEW
              %span Notification
        %li>= link_to "Log Out", destroy_user_session_path, method: :delete

app/views/layouts/_new_notifications.html.haml
-if current_user.new_notifications?
  %span#new-notifications= current_user.new_notifications

app/views/layouts/_sidebar.html.haml
.sidebar-container
  .sm-profile
    = link_to timeline_path(current_user) do
      = image_for(current_user, options = { img_class: "md-img"})
    .info
      = link_to "#{current_user.name}", timeline_path(current_user)
      = link_to "Edit Profile", edit_profile_path(current_user.profile)
  %ul
    %li= link_to "Newsfeed",        newsfeed_path(current_user)
    %li= link_to "Timeline",        timeline_path(current_user)
    %li= link_to "All Users",       users_path
    %li= link_to "Profile",         profile_path(current_user.profile)
    %li= link_to "Friends",         friends_path(current_user)
    %li= link_to "Friend Requests", friend_requests_path(current_user)
    %li= link_to "Find Friends",    find_friends_path(current_user)
    %li= link_to "Notifications",   notifications_path
    %li.divider
    %li= link_to "About",            about_path
    %li= link_to "Contact / Help",   contact_help_path
    %li= link_to "Privacy",          privacy_path
    %li= link_to "Terms of Service", terms_path
    %li.divider
    %li= link_to "Log Out", destroy_user_session_path, method: :delete
    
  %p Odinbook &copy; 2015

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title= page_title(yield(:title))
    = stylesheet_link_tag 'application', media: 'all', 
                                        'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
  %body{ class: "#{params[:controller]}".gsub('devise/', '') }
    %header= yield :header

    - if user_signed_in?
      .header-margin

    .main-holder
      .main-container
        - if user_signed_in?
          .profile= yield(:profile) if content_for?(:profile)
          = render "layouts/flash"
          .info-container
            .sidebar>= yield(:sidebar) if content_for?(:sidebar)
            .content= yield
        - else
          = render "layouts/flash"
          .signup-container
            = yield(:signup) if content_for?(:signup)
            .static-container
              = yield
    
    = render "layouts/footer", controller: params[:controller]

    / = debug(params) if Rails.env.development?

app/views/layouts/profiles.html.haml
= content_for :profile do
  = render "layouts/banner"

= render template: "layouts/users"

app/views/layouts/static_pages.html.haml
- if user_signed_in?
  = render template: "layouts/users"
- else
  - content_for :header do
    = render "devise/shared/login"

  = render template: "layouts/application"

app/views/layouts/user_mailer.html.haml
<!DOCTYPE html>
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}
  %body{style: "background-color: #e9eaed; font-family: Helvetica, Arial, 'lucida grande',tahoma,verdana,arial,sans-serif;"}
    .container{style: "background-color: #fff; width: 600px; margin: 0 auto; border: 1px solid #dcdee3; border-radius: 5px;"}
      = yield

app/views/layouts/users.html.haml
= content_for :header do
  = render "layouts/header"

= content_for :sidebar do
  = render "layouts/sidebar"

= render template: "layouts/application"